project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "HongXin Yang"
  site-url: https://1206708856joker-sys.github.io/Winter-Riesz.github.io/
  
  repo-url: https://github.com/1206708856joker-sys/Winter-Riesz.github.io
  repo-actions: none #[edit, issue]
  
  page-footer:
    right: |
      Made with [Winter-Riesz]
    
  navbar: 
    background: "#A9CCE3"
    search: false
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Books"
        href: books.qmd
      - text: "Blogs"
        href: blog.qmd

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细